name: Flutter

on:
  push:
    branches: [ "dise침oluna" ]
  pull_request:
    branches: [ "dise침oluna" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # Ajusta a la versi칩n que uses

      - name: Install dependencies
        run: flutter pub get

      # Puedes descomentar esto si quieres formateo autom치tico
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
